@Supermercado.Api_HostAddress = http://localhost:5100

GET {{Supermercado.Api_HostAddress}}/categorias
Accept: application/json

###

POST {{Supermercado.Api_HostAddress}}/categorias
Content-Type: application/json

{
  "nome": "Mercearia",
  "descricao": "Alimentos e itens de despensa"
}

###
