@Supermercado.Api_HostAddress = http://localhost:5278

GET {{Supermercado.Api_HostAddress}}/categorias
Accept: application/json

###

POST {{Supermercado.Api_HostAddress}}/categorias
Content-Type: application/json

{
  "nome": "Hortifruti",
  "descricao": "Frutas, verduras e legumes"
}

###


